// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ProjectServiceGetDetailedProjectReader is a Reader for the ProjectServiceGetDetailedProject structure.
type ProjectServiceGetDetailedProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectServiceGetDetailedProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectServiceGetDetailedProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProjectServiceGetDetailedProjectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectServiceGetDetailedProjectOK creates a ProjectServiceGetDetailedProjectOK with default headers values
func NewProjectServiceGetDetailedProjectOK() *ProjectServiceGetDetailedProjectOK {
	return &ProjectServiceGetDetailedProjectOK{}
}

/* ProjectServiceGetDetailedProjectOK describes a response with status code 200, with default header values.

A successful response.
*/
type ProjectServiceGetDetailedProjectOK struct {
	Payload *models.ProjectDetailedProjectsResponse
}

// IsSuccess returns true when this project service get detailed project o k response has a 2xx status code
func (o *ProjectServiceGetDetailedProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this project service get detailed project o k response has a 3xx status code
func (o *ProjectServiceGetDetailedProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this project service get detailed project o k response has a 4xx status code
func (o *ProjectServiceGetDetailedProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this project service get detailed project o k response has a 5xx status code
func (o *ProjectServiceGetDetailedProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this project service get detailed project o k response a status code equal to that given
func (o *ProjectServiceGetDetailedProjectOK) IsCode(code int) bool {
	return code == 200
}

func (o *ProjectServiceGetDetailedProjectOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/detailed][%d] projectServiceGetDetailedProjectOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceGetDetailedProjectOK) String() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/detailed][%d] projectServiceGetDetailedProjectOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceGetDetailedProjectOK) GetPayload() *models.ProjectDetailedProjectsResponse {
	return o.Payload
}

func (o *ProjectServiceGetDetailedProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectDetailedProjectsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectServiceGetDetailedProjectDefault creates a ProjectServiceGetDetailedProjectDefault with default headers values
func NewProjectServiceGetDetailedProjectDefault(code int) *ProjectServiceGetDetailedProjectDefault {
	return &ProjectServiceGetDetailedProjectDefault{
		_statusCode: code,
	}
}

/* ProjectServiceGetDetailedProjectDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ProjectServiceGetDetailedProjectDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the project service get detailed project default response
func (o *ProjectServiceGetDetailedProjectDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this project service get detailed project default response has a 2xx status code
func (o *ProjectServiceGetDetailedProjectDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this project service get detailed project default response has a 3xx status code
func (o *ProjectServiceGetDetailedProjectDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this project service get detailed project default response has a 4xx status code
func (o *ProjectServiceGetDetailedProjectDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this project service get detailed project default response has a 5xx status code
func (o *ProjectServiceGetDetailedProjectDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this project service get detailed project default response a status code equal to that given
func (o *ProjectServiceGetDetailedProjectDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ProjectServiceGetDetailedProjectDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/detailed][%d] ProjectService_GetDetailedProject default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceGetDetailedProjectDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/detailed][%d] ProjectService_GetDetailedProject default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceGetDetailedProjectDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ProjectServiceGetDetailedProjectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
