// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ProjectServiceGetSyncWindowsStateReader is a Reader for the ProjectServiceGetSyncWindowsState structure.
type ProjectServiceGetSyncWindowsStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectServiceGetSyncWindowsStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectServiceGetSyncWindowsStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProjectServiceGetSyncWindowsStateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectServiceGetSyncWindowsStateOK creates a ProjectServiceGetSyncWindowsStateOK with default headers values
func NewProjectServiceGetSyncWindowsStateOK() *ProjectServiceGetSyncWindowsStateOK {
	return &ProjectServiceGetSyncWindowsStateOK{}
}

/* ProjectServiceGetSyncWindowsStateOK describes a response with status code 200, with default header values.

A successful response.
*/
type ProjectServiceGetSyncWindowsStateOK struct {
	Payload *models.ProjectSyncWindowsResponse
}

// IsSuccess returns true when this project service get sync windows state o k response has a 2xx status code
func (o *ProjectServiceGetSyncWindowsStateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this project service get sync windows state o k response has a 3xx status code
func (o *ProjectServiceGetSyncWindowsStateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this project service get sync windows state o k response has a 4xx status code
func (o *ProjectServiceGetSyncWindowsStateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this project service get sync windows state o k response has a 5xx status code
func (o *ProjectServiceGetSyncWindowsStateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this project service get sync windows state o k response a status code equal to that given
func (o *ProjectServiceGetSyncWindowsStateOK) IsCode(code int) bool {
	return code == 200
}

func (o *ProjectServiceGetSyncWindowsStateOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/syncwindows][%d] projectServiceGetSyncWindowsStateOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceGetSyncWindowsStateOK) String() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/syncwindows][%d] projectServiceGetSyncWindowsStateOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceGetSyncWindowsStateOK) GetPayload() *models.ProjectSyncWindowsResponse {
	return o.Payload
}

func (o *ProjectServiceGetSyncWindowsStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectSyncWindowsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectServiceGetSyncWindowsStateDefault creates a ProjectServiceGetSyncWindowsStateDefault with default headers values
func NewProjectServiceGetSyncWindowsStateDefault(code int) *ProjectServiceGetSyncWindowsStateDefault {
	return &ProjectServiceGetSyncWindowsStateDefault{
		_statusCode: code,
	}
}

/* ProjectServiceGetSyncWindowsStateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ProjectServiceGetSyncWindowsStateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the project service get sync windows state default response
func (o *ProjectServiceGetSyncWindowsStateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this project service get sync windows state default response has a 2xx status code
func (o *ProjectServiceGetSyncWindowsStateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this project service get sync windows state default response has a 3xx status code
func (o *ProjectServiceGetSyncWindowsStateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this project service get sync windows state default response has a 4xx status code
func (o *ProjectServiceGetSyncWindowsStateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this project service get sync windows state default response has a 5xx status code
func (o *ProjectServiceGetSyncWindowsStateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this project service get sync windows state default response a status code equal to that given
func (o *ProjectServiceGetSyncWindowsStateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ProjectServiceGetSyncWindowsStateDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/syncwindows][%d] ProjectService_GetSyncWindowsState default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceGetSyncWindowsStateDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/syncwindows][%d] ProjectService_GetSyncWindowsState default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceGetSyncWindowsStateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ProjectServiceGetSyncWindowsStateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
