// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ProjectServiceUpdateReader is a Reader for the ProjectServiceUpdate structure.
type ProjectServiceUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectServiceUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectServiceUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProjectServiceUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectServiceUpdateOK creates a ProjectServiceUpdateOK with default headers values
func NewProjectServiceUpdateOK() *ProjectServiceUpdateOK {
	return &ProjectServiceUpdateOK{}
}

/* ProjectServiceUpdateOK describes a response with status code 200, with default header values.

A successful response.
*/
type ProjectServiceUpdateOK struct {
	Payload *models.V1alpha1AppProject
}

// IsSuccess returns true when this project service update o k response has a 2xx status code
func (o *ProjectServiceUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this project service update o k response has a 3xx status code
func (o *ProjectServiceUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this project service update o k response has a 4xx status code
func (o *ProjectServiceUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this project service update o k response has a 5xx status code
func (o *ProjectServiceUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this project service update o k response a status code equal to that given
func (o *ProjectServiceUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *ProjectServiceUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/projects/{project.metadata.name}][%d] projectServiceUpdateOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceUpdateOK) String() string {
	return fmt.Sprintf("[PUT /api/v1/projects/{project.metadata.name}][%d] projectServiceUpdateOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceUpdateOK) GetPayload() *models.V1alpha1AppProject {
	return o.Payload
}

func (o *ProjectServiceUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1AppProject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectServiceUpdateDefault creates a ProjectServiceUpdateDefault with default headers values
func NewProjectServiceUpdateDefault(code int) *ProjectServiceUpdateDefault {
	return &ProjectServiceUpdateDefault{
		_statusCode: code,
	}
}

/* ProjectServiceUpdateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ProjectServiceUpdateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the project service update default response
func (o *ProjectServiceUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this project service update default response has a 2xx status code
func (o *ProjectServiceUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this project service update default response has a 3xx status code
func (o *ProjectServiceUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this project service update default response has a 4xx status code
func (o *ProjectServiceUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this project service update default response has a 5xx status code
func (o *ProjectServiceUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this project service update default response a status code equal to that given
func (o *ProjectServiceUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ProjectServiceUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /api/v1/projects/{project.metadata.name}][%d] ProjectService_Update default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /api/v1/projects/{project.metadata.name}][%d] ProjectService_Update default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceUpdateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ProjectServiceUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
