// Code generated by go-swagger; DO NOT EDIT.

package cluster_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ClusterServiceListReader is a Reader for the ClusterServiceList structure.
type ClusterServiceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClusterServiceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClusterServiceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewClusterServiceListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewClusterServiceListOK creates a ClusterServiceListOK with default headers values
func NewClusterServiceListOK() *ClusterServiceListOK {
	return &ClusterServiceListOK{}
}

/* ClusterServiceListOK describes a response with status code 200, with default header values.

A successful response.
*/
type ClusterServiceListOK struct {
	Payload *models.V1alpha1ClusterList
}

// IsSuccess returns true when this cluster service list o k response has a 2xx status code
func (o *ClusterServiceListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cluster service list o k response has a 3xx status code
func (o *ClusterServiceListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cluster service list o k response has a 4xx status code
func (o *ClusterServiceListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cluster service list o k response has a 5xx status code
func (o *ClusterServiceListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cluster service list o k response a status code equal to that given
func (o *ClusterServiceListOK) IsCode(code int) bool {
	return code == 200
}

func (o *ClusterServiceListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters][%d] clusterServiceListOK  %+v", 200, o.Payload)
}

func (o *ClusterServiceListOK) String() string {
	return fmt.Sprintf("[GET /api/v1/clusters][%d] clusterServiceListOK  %+v", 200, o.Payload)
}

func (o *ClusterServiceListOK) GetPayload() *models.V1alpha1ClusterList {
	return o.Payload
}

func (o *ClusterServiceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ClusterList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClusterServiceListDefault creates a ClusterServiceListDefault with default headers values
func NewClusterServiceListDefault(code int) *ClusterServiceListDefault {
	return &ClusterServiceListDefault{
		_statusCode: code,
	}
}

/* ClusterServiceListDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ClusterServiceListDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the cluster service list default response
func (o *ClusterServiceListDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this cluster service list default response has a 2xx status code
func (o *ClusterServiceListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cluster service list default response has a 3xx status code
func (o *ClusterServiceListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cluster service list default response has a 4xx status code
func (o *ClusterServiceListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cluster service list default response has a 5xx status code
func (o *ClusterServiceListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cluster service list default response a status code equal to that given
func (o *ClusterServiceListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ClusterServiceListDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters][%d] ClusterService_List default  %+v", o._statusCode, o.Payload)
}

func (o *ClusterServiceListDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/clusters][%d] ClusterService_List default  %+v", o._statusCode, o.Payload)
}

func (o *ClusterServiceListDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ClusterServiceListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
