// Code generated by go-swagger; DO NOT EDIT.

package cluster_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ClusterServiceDeleteReader is a Reader for the ClusterServiceDelete structure.
type ClusterServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClusterServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClusterServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewClusterServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewClusterServiceDeleteOK creates a ClusterServiceDeleteOK with default headers values
func NewClusterServiceDeleteOK() *ClusterServiceDeleteOK {
	return &ClusterServiceDeleteOK{}
}

/* ClusterServiceDeleteOK describes a response with status code 200, with default header values.

A successful response.
*/
type ClusterServiceDeleteOK struct {
	Payload models.ClusterClusterResponse
}

// IsSuccess returns true when this cluster service delete o k response has a 2xx status code
func (o *ClusterServiceDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cluster service delete o k response has a 3xx status code
func (o *ClusterServiceDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cluster service delete o k response has a 4xx status code
func (o *ClusterServiceDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cluster service delete o k response has a 5xx status code
func (o *ClusterServiceDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cluster service delete o k response a status code equal to that given
func (o *ClusterServiceDeleteOK) IsCode(code int) bool {
	return code == 200
}

func (o *ClusterServiceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/clusters/{id.value}][%d] clusterServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ClusterServiceDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/clusters/{id.value}][%d] clusterServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ClusterServiceDeleteOK) GetPayload() models.ClusterClusterResponse {
	return o.Payload
}

func (o *ClusterServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClusterServiceDeleteDefault creates a ClusterServiceDeleteDefault with default headers values
func NewClusterServiceDeleteDefault(code int) *ClusterServiceDeleteDefault {
	return &ClusterServiceDeleteDefault{
		_statusCode: code,
	}
}

/* ClusterServiceDeleteDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ClusterServiceDeleteDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the cluster service delete default response
func (o *ClusterServiceDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this cluster service delete default response has a 2xx status code
func (o *ClusterServiceDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cluster service delete default response has a 3xx status code
func (o *ClusterServiceDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cluster service delete default response has a 4xx status code
func (o *ClusterServiceDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cluster service delete default response has a 5xx status code
func (o *ClusterServiceDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cluster service delete default response a status code equal to that given
func (o *ClusterServiceDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ClusterServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/clusters/{id.value}][%d] ClusterService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ClusterServiceDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /api/v1/clusters/{id.value}][%d] ClusterService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ClusterServiceDeleteDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ClusterServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
