// Code generated by go-swagger; DO NOT EDIT.

package cluster_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ClusterServiceCreateReader is a Reader for the ClusterServiceCreate structure.
type ClusterServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClusterServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClusterServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewClusterServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewClusterServiceCreateOK creates a ClusterServiceCreateOK with default headers values
func NewClusterServiceCreateOK() *ClusterServiceCreateOK {
	return &ClusterServiceCreateOK{}
}

/* ClusterServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type ClusterServiceCreateOK struct {
	Payload *models.V1alpha1Cluster
}

// IsSuccess returns true when this cluster service create o k response has a 2xx status code
func (o *ClusterServiceCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cluster service create o k response has a 3xx status code
func (o *ClusterServiceCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cluster service create o k response has a 4xx status code
func (o *ClusterServiceCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cluster service create o k response has a 5xx status code
func (o *ClusterServiceCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cluster service create o k response a status code equal to that given
func (o *ClusterServiceCreateOK) IsCode(code int) bool {
	return code == 200
}

func (o *ClusterServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] clusterServiceCreateOK  %+v", 200, o.Payload)
}

func (o *ClusterServiceCreateOK) String() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] clusterServiceCreateOK  %+v", 200, o.Payload)
}

func (o *ClusterServiceCreateOK) GetPayload() *models.V1alpha1Cluster {
	return o.Payload
}

func (o *ClusterServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClusterServiceCreateDefault creates a ClusterServiceCreateDefault with default headers values
func NewClusterServiceCreateDefault(code int) *ClusterServiceCreateDefault {
	return &ClusterServiceCreateDefault{
		_statusCode: code,
	}
}

/* ClusterServiceCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ClusterServiceCreateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the cluster service create default response
func (o *ClusterServiceCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this cluster service create default response has a 2xx status code
func (o *ClusterServiceCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cluster service create default response has a 3xx status code
func (o *ClusterServiceCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cluster service create default response has a 4xx status code
func (o *ClusterServiceCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cluster service create default response has a 5xx status code
func (o *ClusterServiceCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cluster service create default response a status code equal to that given
func (o *ClusterServiceCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ClusterServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] ClusterService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *ClusterServiceCreateDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] ClusterService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *ClusterServiceCreateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ClusterServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
