// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationFileChunk application file chunk
//
// swagger:model applicationFileChunk
type ApplicationFileChunk struct {

	// chunk
	// Format: byte
	Chunk strfmt.Base64 `json:"chunk,omitempty"`
}

// Validate validates this application file chunk
func (m *ApplicationFileChunk) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this application file chunk based on context it is used
func (m *ApplicationFileChunk) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationFileChunk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationFileChunk) UnmarshalBinary(b []byte) error {
	var res ApplicationFileChunk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
