// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NotificationTemplate notification template
//
// swagger:model notificationTemplate
type NotificationTemplate struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this notification template
func (m *NotificationTemplate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this notification template based on context it is used
func (m *NotificationTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NotificationTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationTemplate) UnmarshalBinary(b []byte) error {
	var res NotificationTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
