// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NotificationService notification service
//
// swagger:model notificationService
type NotificationService struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this notification service
func (m *NotificationService) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this notification service based on context it is used
func (m *NotificationService) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NotificationService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationService) UnmarshalBinary(b []byte) error {
	var res NotificationService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
