// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1JSON JSON represents any valid JSON value.
// These types are supported: bool, int64, float64, string, []interface{}, map[string]interface{} and nil.
//
// swagger:model v1JSON
type V1JSON struct {

	// raw
	// Format: byte
	Raw strfmt.Base64 `json:"raw,omitempty"`
}

// Validate validates this v1 JSON
func (m *V1JSON) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 JSON based on context it is used
func (m *V1JSON) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1JSON) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1JSON) UnmarshalBinary(b []byte) error {
	var res V1JSON
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
