// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1PullRequestGeneratorGitLab PullRequestGeneratorGitLab defines connection info specific to GitLab.
//
// swagger:model v1alpha1PullRequestGeneratorGitLab
type V1alpha1PullRequestGeneratorGitLab struct {

	// The GitLab API URL to talk to. If blank, uses https://gitlab.com/.
	API string `json:"api,omitempty"`

	// Labels is used to filter the MRs that you want to target
	Labels []string `json:"labels"`

	// GitLab project to scan. Required.
	Project string `json:"project,omitempty"`

	// PullRequestState is an additional MRs filter to get only those with a certain state. Default: "" (all states)
	PullRequestState string `json:"pullRequestState,omitempty"`

	// token ref
	TokenRef *V1alpha1SecretRef `json:"tokenRef,omitempty"`
}

// Validate validates this v1alpha1 pull request generator git lab
func (m *V1alpha1PullRequestGeneratorGitLab) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTokenRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1PullRequestGeneratorGitLab) validateTokenRef(formats strfmt.Registry) error {
	if swag.IsZero(m.TokenRef) { // not required
		return nil
	}

	if m.TokenRef != nil {
		if err := m.TokenRef.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tokenRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tokenRef")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 pull request generator git lab based on the context it is used
func (m *V1alpha1PullRequestGeneratorGitLab) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTokenRef(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1PullRequestGeneratorGitLab) contextValidateTokenRef(ctx context.Context, formats strfmt.Registry) error {

	if m.TokenRef != nil {
		if err := m.TokenRef.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tokenRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tokenRef")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1PullRequestGeneratorGitLab) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1PullRequestGeneratorGitLab) UnmarshalBinary(b []byte) error {
	var res V1alpha1PullRequestGeneratorGitLab
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
