// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1GitDirectoryGeneratorItem v1alpha1 git directory generator item
//
// swagger:model v1alpha1GitDirectoryGeneratorItem
type V1alpha1GitDirectoryGeneratorItem struct {

	// exclude
	Exclude bool `json:"exclude,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this v1alpha1 git directory generator item
func (m *V1alpha1GitDirectoryGeneratorItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 git directory generator item based on context it is used
func (m *V1alpha1GitDirectoryGeneratorItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1GitDirectoryGeneratorItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1GitDirectoryGeneratorItem) UnmarshalBinary(b []byte) error {
	var res V1alpha1GitDirectoryGeneratorItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
