// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1PullRequestGeneratorFilter PullRequestGeneratorFilter is a single pull request filter.
// If multiple filter types are set on a single struct, they will be AND'd together. All filters must
// pass for a pull request to be included.
//
// swagger:model v1alpha1PullRequestGeneratorFilter
type V1alpha1PullRequestGeneratorFilter struct {

	// branch match
	BranchMatch string `json:"branchMatch,omitempty"`
}

// Validate validates this v1alpha1 pull request generator filter
func (m *V1alpha1PullRequestGeneratorFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 pull request generator filter based on context it is used
func (m *V1alpha1PullRequestGeneratorFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1PullRequestGeneratorFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1PullRequestGeneratorFilter) UnmarshalBinary(b []byte) error {
	var res V1alpha1PullRequestGeneratorFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
