// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SecretRef Utility struct for a reference to a secret key.
//
// swagger:model v1alpha1SecretRef
type V1alpha1SecretRef struct {

	// key
	Key string `json:"key,omitempty"`

	// secret name
	SecretName string `json:"secretName,omitempty"`
}

// Validate validates this v1alpha1 secret ref
func (m *V1alpha1SecretRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 secret ref based on context it is used
func (m *V1alpha1SecretRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SecretRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SecretRef) UnmarshalBinary(b []byte) error {
	var res V1alpha1SecretRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
