// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SCMProviderGeneratorGitea SCMProviderGeneratorGitea defines a connection info specific to Gitea.
//
// swagger:model v1alpha1SCMProviderGeneratorGitea
type V1alpha1SCMProviderGeneratorGitea struct {

	// Scan all branches instead of just the default branch.
	AllBranches bool `json:"allBranches,omitempty"`

	// The Gitea URL to talk to. For example https://gitea.mydomain.com/.
	API string `json:"api,omitempty"`

	// Allow self-signed TLS / Certificates; default: false
	Insecure bool `json:"insecure,omitempty"`

	// Gitea organization or user to scan. Required.
	Owner string `json:"owner,omitempty"`

	// token ref
	TokenRef *V1alpha1SecretRef `json:"tokenRef,omitempty"`
}

// Validate validates this v1alpha1 s c m provider generator gitea
func (m *V1alpha1SCMProviderGeneratorGitea) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTokenRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1SCMProviderGeneratorGitea) validateTokenRef(formats strfmt.Registry) error {
	if swag.IsZero(m.TokenRef) { // not required
		return nil
	}

	if m.TokenRef != nil {
		if err := m.TokenRef.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tokenRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tokenRef")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 s c m provider generator gitea based on the context it is used
func (m *V1alpha1SCMProviderGeneratorGitea) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTokenRef(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1SCMProviderGeneratorGitea) contextValidateTokenRef(ctx context.Context, formats strfmt.Registry) error {

	if m.TokenRef != nil {
		if err := m.TokenRef.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tokenRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tokenRef")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SCMProviderGeneratorGitea) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SCMProviderGeneratorGitea) UnmarshalBinary(b []byte) error {
	var res V1alpha1SCMProviderGeneratorGitea
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
