// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSetTemplateMeta ApplicationSetTemplateMeta represents the Argo CD application fields that may
// be used for Applications generated from the ApplicationSet (based on metav1.ObjectMeta)
//
// swagger:model v1alpha1ApplicationSetTemplateMeta
type V1alpha1ApplicationSetTemplateMeta struct {

	// annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// finalizers
	Finalizers []string `json:"finalizers"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this v1alpha1 application set template meta
func (m *V1alpha1ApplicationSetTemplateMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 application set template meta based on context it is used
func (m *V1alpha1ApplicationSetTemplateMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSetTemplateMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSetTemplateMeta) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSetTemplateMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
