// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSetSyncPolicy ApplicationSetSyncPolicy configures how generated Applications will relate to their
// ApplicationSet.
//
// swagger:model v1alpha1ApplicationSetSyncPolicy
type V1alpha1ApplicationSetSyncPolicy struct {

	// PreserveResourcesOnDeletion will preserve resources on deletion. If PreserveResourcesOnDeletion is set to true, these Applications will not be deleted.
	PreserveResourcesOnDeletion bool `json:"preserveResourcesOnDeletion,omitempty"`
}

// Validate validates this v1alpha1 application set sync policy
func (m *V1alpha1ApplicationSetSyncPolicy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 application set sync policy based on context it is used
func (m *V1alpha1ApplicationSetSyncPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSetSyncPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSetSyncPolicy) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSetSyncPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
