// Code generated by go-swagger; DO NOT EDIT.

package application_set_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationSetServiceDeleteReader is a Reader for the ApplicationSetServiceDelete structure.
type ApplicationSetServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationSetServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationSetServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationSetServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationSetServiceDeleteOK creates a ApplicationSetServiceDeleteOK with default headers values
func NewApplicationSetServiceDeleteOK() *ApplicationSetServiceDeleteOK {
	return &ApplicationSetServiceDeleteOK{}
}

/* ApplicationSetServiceDeleteOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationSetServiceDeleteOK struct {
	Payload *models.ApplicationsetApplicationSetResponse
}

// IsSuccess returns true when this application set service delete o k response has a 2xx status code
func (o *ApplicationSetServiceDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application set service delete o k response has a 3xx status code
func (o *ApplicationSetServiceDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application set service delete o k response has a 4xx status code
func (o *ApplicationSetServiceDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application set service delete o k response has a 5xx status code
func (o *ApplicationSetServiceDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application set service delete o k response a status code equal to that given
func (o *ApplicationSetServiceDeleteOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationSetServiceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/applicationsets/{name}][%d] applicationSetServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ApplicationSetServiceDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/applicationsets/{name}][%d] applicationSetServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ApplicationSetServiceDeleteOK) GetPayload() *models.ApplicationsetApplicationSetResponse {
	return o.Payload
}

func (o *ApplicationSetServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationsetApplicationSetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationSetServiceDeleteDefault creates a ApplicationSetServiceDeleteDefault with default headers values
func NewApplicationSetServiceDeleteDefault(code int) *ApplicationSetServiceDeleteDefault {
	return &ApplicationSetServiceDeleteDefault{
		_statusCode: code,
	}
}

/* ApplicationSetServiceDeleteDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationSetServiceDeleteDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application set service delete default response
func (o *ApplicationSetServiceDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application set service delete default response has a 2xx status code
func (o *ApplicationSetServiceDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application set service delete default response has a 3xx status code
func (o *ApplicationSetServiceDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application set service delete default response has a 4xx status code
func (o *ApplicationSetServiceDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application set service delete default response has a 5xx status code
func (o *ApplicationSetServiceDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application set service delete default response a status code equal to that given
func (o *ApplicationSetServiceDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationSetServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/applicationsets/{name}][%d] ApplicationSetService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationSetServiceDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /api/v1/applicationsets/{name}][%d] ApplicationSetService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationSetServiceDeleteDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationSetServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
