// Code generated by go-swagger; DO NOT EDIT.

package application_set_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationSetServiceListReader is a Reader for the ApplicationSetServiceList structure.
type ApplicationSetServiceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationSetServiceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationSetServiceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationSetServiceListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationSetServiceListOK creates a ApplicationSetServiceListOK with default headers values
func NewApplicationSetServiceListOK() *ApplicationSetServiceListOK {
	return &ApplicationSetServiceListOK{}
}

/* ApplicationSetServiceListOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationSetServiceListOK struct {
	Payload *models.V1alpha1ApplicationSetList
}

// IsSuccess returns true when this application set service list o k response has a 2xx status code
func (o *ApplicationSetServiceListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application set service list o k response has a 3xx status code
func (o *ApplicationSetServiceListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application set service list o k response has a 4xx status code
func (o *ApplicationSetServiceListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application set service list o k response has a 5xx status code
func (o *ApplicationSetServiceListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application set service list o k response a status code equal to that given
func (o *ApplicationSetServiceListOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationSetServiceListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applicationsets][%d] applicationSetServiceListOK  %+v", 200, o.Payload)
}

func (o *ApplicationSetServiceListOK) String() string {
	return fmt.Sprintf("[GET /api/v1/applicationsets][%d] applicationSetServiceListOK  %+v", 200, o.Payload)
}

func (o *ApplicationSetServiceListOK) GetPayload() *models.V1alpha1ApplicationSetList {
	return o.Payload
}

func (o *ApplicationSetServiceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ApplicationSetList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationSetServiceListDefault creates a ApplicationSetServiceListDefault with default headers values
func NewApplicationSetServiceListDefault(code int) *ApplicationSetServiceListDefault {
	return &ApplicationSetServiceListDefault{
		_statusCode: code,
	}
}

/* ApplicationSetServiceListDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationSetServiceListDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application set service list default response
func (o *ApplicationSetServiceListDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application set service list default response has a 2xx status code
func (o *ApplicationSetServiceListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application set service list default response has a 3xx status code
func (o *ApplicationSetServiceListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application set service list default response has a 4xx status code
func (o *ApplicationSetServiceListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application set service list default response has a 5xx status code
func (o *ApplicationSetServiceListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application set service list default response a status code equal to that given
func (o *ApplicationSetServiceListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationSetServiceListDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/applicationsets][%d] ApplicationSetService_List default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationSetServiceListDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/applicationsets][%d] ApplicationSetService_List default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationSetServiceListDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationSetServiceListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
