// Code generated by go-swagger; DO NOT EDIT.

package application_set_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationSetServiceCreateReader is a Reader for the ApplicationSetServiceCreate structure.
type ApplicationSetServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationSetServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationSetServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationSetServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationSetServiceCreateOK creates a ApplicationSetServiceCreateOK with default headers values
func NewApplicationSetServiceCreateOK() *ApplicationSetServiceCreateOK {
	return &ApplicationSetServiceCreateOK{}
}

/* ApplicationSetServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationSetServiceCreateOK struct {
	Payload *models.V1alpha1ApplicationSet
}

// IsSuccess returns true when this application set service create o k response has a 2xx status code
func (o *ApplicationSetServiceCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application set service create o k response has a 3xx status code
func (o *ApplicationSetServiceCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application set service create o k response has a 4xx status code
func (o *ApplicationSetServiceCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application set service create o k response has a 5xx status code
func (o *ApplicationSetServiceCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application set service create o k response a status code equal to that given
func (o *ApplicationSetServiceCreateOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationSetServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applicationsets][%d] applicationSetServiceCreateOK  %+v", 200, o.Payload)
}

func (o *ApplicationSetServiceCreateOK) String() string {
	return fmt.Sprintf("[POST /api/v1/applicationsets][%d] applicationSetServiceCreateOK  %+v", 200, o.Payload)
}

func (o *ApplicationSetServiceCreateOK) GetPayload() *models.V1alpha1ApplicationSet {
	return o.Payload
}

func (o *ApplicationSetServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ApplicationSet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationSetServiceCreateDefault creates a ApplicationSetServiceCreateDefault with default headers values
func NewApplicationSetServiceCreateDefault(code int) *ApplicationSetServiceCreateDefault {
	return &ApplicationSetServiceCreateDefault{
		_statusCode: code,
	}
}

/* ApplicationSetServiceCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationSetServiceCreateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application set service create default response
func (o *ApplicationSetServiceCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application set service create default response has a 2xx status code
func (o *ApplicationSetServiceCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application set service create default response has a 3xx status code
func (o *ApplicationSetServiceCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application set service create default response has a 4xx status code
func (o *ApplicationSetServiceCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application set service create default response has a 5xx status code
func (o *ApplicationSetServiceCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application set service create default response a status code equal to that given
func (o *ApplicationSetServiceCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationSetServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/applicationsets][%d] ApplicationSetService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationSetServiceCreateDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/applicationsets][%d] ApplicationSetService_Create default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationSetServiceCreateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationSetServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
