// Code generated by go-swagger; DO NOT EDIT.

package certificate_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// CertificateServiceCreateCertificateReader is a Reader for the CertificateServiceCreateCertificate structure.
type CertificateServiceCreateCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CertificateServiceCreateCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCertificateServiceCreateCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCertificateServiceCreateCertificateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCertificateServiceCreateCertificateOK creates a CertificateServiceCreateCertificateOK with default headers values
func NewCertificateServiceCreateCertificateOK() *CertificateServiceCreateCertificateOK {
	return &CertificateServiceCreateCertificateOK{}
}

/* CertificateServiceCreateCertificateOK describes a response with status code 200, with default header values.

A successful response.
*/
type CertificateServiceCreateCertificateOK struct {
	Payload *models.V1alpha1RepositoryCertificateList
}

// IsSuccess returns true when this certificate service create certificate o k response has a 2xx status code
func (o *CertificateServiceCreateCertificateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this certificate service create certificate o k response has a 3xx status code
func (o *CertificateServiceCreateCertificateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this certificate service create certificate o k response has a 4xx status code
func (o *CertificateServiceCreateCertificateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this certificate service create certificate o k response has a 5xx status code
func (o *CertificateServiceCreateCertificateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this certificate service create certificate o k response a status code equal to that given
func (o *CertificateServiceCreateCertificateOK) IsCode(code int) bool {
	return code == 200
}

func (o *CertificateServiceCreateCertificateOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/certificates][%d] certificateServiceCreateCertificateOK  %+v", 200, o.Payload)
}

func (o *CertificateServiceCreateCertificateOK) String() string {
	return fmt.Sprintf("[POST /api/v1/certificates][%d] certificateServiceCreateCertificateOK  %+v", 200, o.Payload)
}

func (o *CertificateServiceCreateCertificateOK) GetPayload() *models.V1alpha1RepositoryCertificateList {
	return o.Payload
}

func (o *CertificateServiceCreateCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepositoryCertificateList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCertificateServiceCreateCertificateDefault creates a CertificateServiceCreateCertificateDefault with default headers values
func NewCertificateServiceCreateCertificateDefault(code int) *CertificateServiceCreateCertificateDefault {
	return &CertificateServiceCreateCertificateDefault{
		_statusCode: code,
	}
}

/* CertificateServiceCreateCertificateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CertificateServiceCreateCertificateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the certificate service create certificate default response
func (o *CertificateServiceCreateCertificateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this certificate service create certificate default response has a 2xx status code
func (o *CertificateServiceCreateCertificateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this certificate service create certificate default response has a 3xx status code
func (o *CertificateServiceCreateCertificateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this certificate service create certificate default response has a 4xx status code
func (o *CertificateServiceCreateCertificateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this certificate service create certificate default response has a 5xx status code
func (o *CertificateServiceCreateCertificateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this certificate service create certificate default response a status code equal to that given
func (o *CertificateServiceCreateCertificateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CertificateServiceCreateCertificateDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/certificates][%d] CertificateService_CreateCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *CertificateServiceCreateCertificateDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/certificates][%d] CertificateService_CreateCertificate default  %+v", o._statusCode, o.Payload)
}

func (o *CertificateServiceCreateCertificateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *CertificateServiceCreateCertificateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
