// Code generated by go-swagger; DO NOT EDIT.

package g_p_g_key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// GPGKeyServiceListReader is a Reader for the GPGKeyServiceList structure.
type GPGKeyServiceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GPGKeyServiceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGPGKeyServiceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGPGKeyServiceListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGPGKeyServiceListOK creates a GPGKeyServiceListOK with default headers values
func NewGPGKeyServiceListOK() *GPGKeyServiceListOK {
	return &GPGKeyServiceListOK{}
}

/* GPGKeyServiceListOK describes a response with status code 200, with default header values.

A successful response.
*/
type GPGKeyServiceListOK struct {
	Payload *models.V1alpha1GnuPGPublicKeyList
}

// IsSuccess returns true when this g p g key service list o k response has a 2xx status code
func (o *GPGKeyServiceListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this g p g key service list o k response has a 3xx status code
func (o *GPGKeyServiceListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this g p g key service list o k response has a 4xx status code
func (o *GPGKeyServiceListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this g p g key service list o k response has a 5xx status code
func (o *GPGKeyServiceListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this g p g key service list o k response a status code equal to that given
func (o *GPGKeyServiceListOK) IsCode(code int) bool {
	return code == 200
}

func (o *GPGKeyServiceListOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/gpgkeys][%d] gPGKeyServiceListOK  %+v", 200, o.Payload)
}

func (o *GPGKeyServiceListOK) String() string {
	return fmt.Sprintf("[GET /api/v1/gpgkeys][%d] gPGKeyServiceListOK  %+v", 200, o.Payload)
}

func (o *GPGKeyServiceListOK) GetPayload() *models.V1alpha1GnuPGPublicKeyList {
	return o.Payload
}

func (o *GPGKeyServiceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1GnuPGPublicKeyList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGPGKeyServiceListDefault creates a GPGKeyServiceListDefault with default headers values
func NewGPGKeyServiceListDefault(code int) *GPGKeyServiceListDefault {
	return &GPGKeyServiceListDefault{
		_statusCode: code,
	}
}

/* GPGKeyServiceListDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GPGKeyServiceListDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the g p g key service list default response
func (o *GPGKeyServiceListDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this g p g key service list default response has a 2xx status code
func (o *GPGKeyServiceListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this g p g key service list default response has a 3xx status code
func (o *GPGKeyServiceListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this g p g key service list default response has a 4xx status code
func (o *GPGKeyServiceListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this g p g key service list default response has a 5xx status code
func (o *GPGKeyServiceListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this g p g key service list default response a status code equal to that given
func (o *GPGKeyServiceListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GPGKeyServiceListDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/gpgkeys][%d] GPGKeyService_List default  %+v", o._statusCode, o.Payload)
}

func (o *GPGKeyServiceListDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/gpgkeys][%d] GPGKeyService_List default  %+v", o._statusCode, o.Payload)
}

func (o *GPGKeyServiceListDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *GPGKeyServiceListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
