// Code generated by go-swagger; DO NOT EDIT.

package notification_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// NotificationServiceListServicesReader is a Reader for the NotificationServiceListServices structure.
type NotificationServiceListServicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotificationServiceListServicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNotificationServiceListServicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNotificationServiceListServicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNotificationServiceListServicesOK creates a NotificationServiceListServicesOK with default headers values
func NewNotificationServiceListServicesOK() *NotificationServiceListServicesOK {
	return &NotificationServiceListServicesOK{}
}

/* NotificationServiceListServicesOK describes a response with status code 200, with default header values.

A successful response.
*/
type NotificationServiceListServicesOK struct {
	Payload *models.NotificationServiceList
}

// IsSuccess returns true when this notification service list services o k response has a 2xx status code
func (o *NotificationServiceListServicesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this notification service list services o k response has a 3xx status code
func (o *NotificationServiceListServicesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this notification service list services o k response has a 4xx status code
func (o *NotificationServiceListServicesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this notification service list services o k response has a 5xx status code
func (o *NotificationServiceListServicesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this notification service list services o k response a status code equal to that given
func (o *NotificationServiceListServicesOK) IsCode(code int) bool {
	return code == 200
}

func (o *NotificationServiceListServicesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/notifications/services][%d] notificationServiceListServicesOK  %+v", 200, o.Payload)
}

func (o *NotificationServiceListServicesOK) String() string {
	return fmt.Sprintf("[GET /api/v1/notifications/services][%d] notificationServiceListServicesOK  %+v", 200, o.Payload)
}

func (o *NotificationServiceListServicesOK) GetPayload() *models.NotificationServiceList {
	return o.Payload
}

func (o *NotificationServiceListServicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotificationServiceList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationServiceListServicesDefault creates a NotificationServiceListServicesDefault with default headers values
func NewNotificationServiceListServicesDefault(code int) *NotificationServiceListServicesDefault {
	return &NotificationServiceListServicesDefault{
		_statusCode: code,
	}
}

/* NotificationServiceListServicesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type NotificationServiceListServicesDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the notification service list services default response
func (o *NotificationServiceListServicesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this notification service list services default response has a 2xx status code
func (o *NotificationServiceListServicesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this notification service list services default response has a 3xx status code
func (o *NotificationServiceListServicesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this notification service list services default response has a 4xx status code
func (o *NotificationServiceListServicesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this notification service list services default response has a 5xx status code
func (o *NotificationServiceListServicesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this notification service list services default response a status code equal to that given
func (o *NotificationServiceListServicesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *NotificationServiceListServicesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/notifications/services][%d] NotificationService_ListServices default  %+v", o._statusCode, o.Payload)
}

func (o *NotificationServiceListServicesDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/notifications/services][%d] NotificationService_ListServices default  %+v", o._statusCode, o.Payload)
}

func (o *NotificationServiceListServicesDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *NotificationServiceListServicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
