// Code generated by go-swagger; DO NOT EDIT.

package notification_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNotificationServiceListTriggersParams creates a new NotificationServiceListTriggersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotificationServiceListTriggersParams() *NotificationServiceListTriggersParams {
	return &NotificationServiceListTriggersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationServiceListTriggersParamsWithTimeout creates a new NotificationServiceListTriggersParams object
// with the ability to set a timeout on a request.
func NewNotificationServiceListTriggersParamsWithTimeout(timeout time.Duration) *NotificationServiceListTriggersParams {
	return &NotificationServiceListTriggersParams{
		timeout: timeout,
	}
}

// NewNotificationServiceListTriggersParamsWithContext creates a new NotificationServiceListTriggersParams object
// with the ability to set a context for a request.
func NewNotificationServiceListTriggersParamsWithContext(ctx context.Context) *NotificationServiceListTriggersParams {
	return &NotificationServiceListTriggersParams{
		Context: ctx,
	}
}

// NewNotificationServiceListTriggersParamsWithHTTPClient creates a new NotificationServiceListTriggersParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotificationServiceListTriggersParamsWithHTTPClient(client *http.Client) *NotificationServiceListTriggersParams {
	return &NotificationServiceListTriggersParams{
		HTTPClient: client,
	}
}

/* NotificationServiceListTriggersParams contains all the parameters to send to the API endpoint
   for the notification service list triggers operation.

   Typically these are written to a http.Request.
*/
type NotificationServiceListTriggersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notification service list triggers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationServiceListTriggersParams) WithDefaults() *NotificationServiceListTriggersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notification service list triggers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationServiceListTriggersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notification service list triggers params
func (o *NotificationServiceListTriggersParams) WithTimeout(timeout time.Duration) *NotificationServiceListTriggersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notification service list triggers params
func (o *NotificationServiceListTriggersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notification service list triggers params
func (o *NotificationServiceListTriggersParams) WithContext(ctx context.Context) *NotificationServiceListTriggersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notification service list triggers params
func (o *NotificationServiceListTriggersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notification service list triggers params
func (o *NotificationServiceListTriggersParams) WithHTTPClient(client *http.Client) *NotificationServiceListTriggersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notification service list triggers params
func (o *NotificationServiceListTriggersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationServiceListTriggersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
