// Code generated by go-swagger; DO NOT EDIT.

package session_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// SessionServiceDeleteReader is a Reader for the SessionServiceDelete structure.
type SessionServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSessionServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSessionServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSessionServiceDeleteOK creates a SessionServiceDeleteOK with default headers values
func NewSessionServiceDeleteOK() *SessionServiceDeleteOK {
	return &SessionServiceDeleteOK{}
}

/* SessionServiceDeleteOK describes a response with status code 200, with default header values.

A successful response.
*/
type SessionServiceDeleteOK struct {
	Payload *models.SessionSessionResponse
}

// IsSuccess returns true when this session service delete o k response has a 2xx status code
func (o *SessionServiceDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this session service delete o k response has a 3xx status code
func (o *SessionServiceDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this session service delete o k response has a 4xx status code
func (o *SessionServiceDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this session service delete o k response has a 5xx status code
func (o *SessionServiceDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this session service delete o k response a status code equal to that given
func (o *SessionServiceDeleteOK) IsCode(code int) bool {
	return code == 200
}

func (o *SessionServiceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/session][%d] sessionServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *SessionServiceDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/session][%d] sessionServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *SessionServiceDeleteOK) GetPayload() *models.SessionSessionResponse {
	return o.Payload
}

func (o *SessionServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionSessionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSessionServiceDeleteDefault creates a SessionServiceDeleteDefault with default headers values
func NewSessionServiceDeleteDefault(code int) *SessionServiceDeleteDefault {
	return &SessionServiceDeleteDefault{
		_statusCode: code,
	}
}

/* SessionServiceDeleteDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SessionServiceDeleteDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the session service delete default response
func (o *SessionServiceDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this session service delete default response has a 2xx status code
func (o *SessionServiceDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this session service delete default response has a 3xx status code
func (o *SessionServiceDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this session service delete default response has a 4xx status code
func (o *SessionServiceDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this session service delete default response has a 5xx status code
func (o *SessionServiceDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this session service delete default response a status code equal to that given
func (o *SessionServiceDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SessionServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/session][%d] SessionService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *SessionServiceDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /api/v1/session][%d] SessionService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *SessionServiceDeleteDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *SessionServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
