// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationServiceGetResourceReader is a Reader for the ApplicationServiceGetResource structure.
type ApplicationServiceGetResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceGetResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceGetResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceGetResourceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceGetResourceOK creates a ApplicationServiceGetResourceOK with default headers values
func NewApplicationServiceGetResourceOK() *ApplicationServiceGetResourceOK {
	return &ApplicationServiceGetResourceOK{}
}

/* ApplicationServiceGetResourceOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceGetResourceOK struct {
	Payload *models.ApplicationApplicationResourceResponse
}

// IsSuccess returns true when this application service get resource o k response has a 2xx status code
func (o *ApplicationServiceGetResourceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application service get resource o k response has a 3xx status code
func (o *ApplicationServiceGetResourceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application service get resource o k response has a 4xx status code
func (o *ApplicationServiceGetResourceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application service get resource o k response has a 5xx status code
func (o *ApplicationServiceGetResourceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application service get resource o k response a status code equal to that given
func (o *ApplicationServiceGetResourceOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationServiceGetResourceOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource][%d] applicationServiceGetResourceOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceGetResourceOK) String() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource][%d] applicationServiceGetResourceOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceGetResourceOK) GetPayload() *models.ApplicationApplicationResourceResponse {
	return o.Payload
}

func (o *ApplicationServiceGetResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationApplicationResourceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceGetResourceDefault creates a ApplicationServiceGetResourceDefault with default headers values
func NewApplicationServiceGetResourceDefault(code int) *ApplicationServiceGetResourceDefault {
	return &ApplicationServiceGetResourceDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceGetResourceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceGetResourceDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service get resource default response
func (o *ApplicationServiceGetResourceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application service get resource default response has a 2xx status code
func (o *ApplicationServiceGetResourceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application service get resource default response has a 3xx status code
func (o *ApplicationServiceGetResourceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application service get resource default response has a 4xx status code
func (o *ApplicationServiceGetResourceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application service get resource default response has a 5xx status code
func (o *ApplicationServiceGetResourceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application service get resource default response a status code equal to that given
func (o *ApplicationServiceGetResourceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationServiceGetResourceDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource][%d] ApplicationService_GetResource default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceGetResourceDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource][%d] ApplicationService_GetResource default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceGetResourceDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceGetResourceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
