// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// NewApplicationServiceGetManifestsWithFilesParams creates a new ApplicationServiceGetManifestsWithFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationServiceGetManifestsWithFilesParams() *ApplicationServiceGetManifestsWithFilesParams {
	return &ApplicationServiceGetManifestsWithFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationServiceGetManifestsWithFilesParamsWithTimeout creates a new ApplicationServiceGetManifestsWithFilesParams object
// with the ability to set a timeout on a request.
func NewApplicationServiceGetManifestsWithFilesParamsWithTimeout(timeout time.Duration) *ApplicationServiceGetManifestsWithFilesParams {
	return &ApplicationServiceGetManifestsWithFilesParams{
		timeout: timeout,
	}
}

// NewApplicationServiceGetManifestsWithFilesParamsWithContext creates a new ApplicationServiceGetManifestsWithFilesParams object
// with the ability to set a context for a request.
func NewApplicationServiceGetManifestsWithFilesParamsWithContext(ctx context.Context) *ApplicationServiceGetManifestsWithFilesParams {
	return &ApplicationServiceGetManifestsWithFilesParams{
		Context: ctx,
	}
}

// NewApplicationServiceGetManifestsWithFilesParamsWithHTTPClient creates a new ApplicationServiceGetManifestsWithFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationServiceGetManifestsWithFilesParamsWithHTTPClient(client *http.Client) *ApplicationServiceGetManifestsWithFilesParams {
	return &ApplicationServiceGetManifestsWithFilesParams{
		HTTPClient: client,
	}
}

/* ApplicationServiceGetManifestsWithFilesParams contains all the parameters to send to the API endpoint
   for the application service get manifests with files operation.

   Typically these are written to a http.Request.
*/
type ApplicationServiceGetManifestsWithFilesParams struct {

	/* Body.

	   (streaming inputs)
	*/
	Body *models.ApplicationApplicationManifestQueryWithFilesWrapper

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application service get manifests with files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceGetManifestsWithFilesParams) WithDefaults() *ApplicationServiceGetManifestsWithFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application service get manifests with files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceGetManifestsWithFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) WithTimeout(timeout time.Duration) *ApplicationServiceGetManifestsWithFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) WithContext(ctx context.Context) *ApplicationServiceGetManifestsWithFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) WithHTTPClient(client *http.Client) *ApplicationServiceGetManifestsWithFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) WithBody(body *models.ApplicationApplicationManifestQueryWithFilesWrapper) *ApplicationServiceGetManifestsWithFilesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the application service get manifests with files params
func (o *ApplicationServiceGetManifestsWithFilesParams) SetBody(body *models.ApplicationApplicationManifestQueryWithFilesWrapper) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationServiceGetManifestsWithFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
