// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationServiceUpdateSpecReader is a Reader for the ApplicationServiceUpdateSpec structure.
type ApplicationServiceUpdateSpecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceUpdateSpecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceUpdateSpecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceUpdateSpecDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceUpdateSpecOK creates a ApplicationServiceUpdateSpecOK with default headers values
func NewApplicationServiceUpdateSpecOK() *ApplicationServiceUpdateSpecOK {
	return &ApplicationServiceUpdateSpecOK{}
}

/* ApplicationServiceUpdateSpecOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceUpdateSpecOK struct {
	Payload *models.V1alpha1ApplicationSpec
}

// IsSuccess returns true when this application service update spec o k response has a 2xx status code
func (o *ApplicationServiceUpdateSpecOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application service update spec o k response has a 3xx status code
func (o *ApplicationServiceUpdateSpecOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application service update spec o k response has a 4xx status code
func (o *ApplicationServiceUpdateSpecOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application service update spec o k response has a 5xx status code
func (o *ApplicationServiceUpdateSpecOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application service update spec o k response a status code equal to that given
func (o *ApplicationServiceUpdateSpecOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationServiceUpdateSpecOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/applications/{name}/spec][%d] applicationServiceUpdateSpecOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceUpdateSpecOK) String() string {
	return fmt.Sprintf("[PUT /api/v1/applications/{name}/spec][%d] applicationServiceUpdateSpecOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceUpdateSpecOK) GetPayload() *models.V1alpha1ApplicationSpec {
	return o.Payload
}

func (o *ApplicationServiceUpdateSpecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ApplicationSpec)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceUpdateSpecDefault creates a ApplicationServiceUpdateSpecDefault with default headers values
func NewApplicationServiceUpdateSpecDefault(code int) *ApplicationServiceUpdateSpecDefault {
	return &ApplicationServiceUpdateSpecDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceUpdateSpecDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceUpdateSpecDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service update spec default response
func (o *ApplicationServiceUpdateSpecDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application service update spec default response has a 2xx status code
func (o *ApplicationServiceUpdateSpecDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application service update spec default response has a 3xx status code
func (o *ApplicationServiceUpdateSpecDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application service update spec default response has a 4xx status code
func (o *ApplicationServiceUpdateSpecDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application service update spec default response has a 5xx status code
func (o *ApplicationServiceUpdateSpecDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application service update spec default response a status code equal to that given
func (o *ApplicationServiceUpdateSpecDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationServiceUpdateSpecDefault) Error() string {
	return fmt.Sprintf("[PUT /api/v1/applications/{name}/spec][%d] ApplicationService_UpdateSpec default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceUpdateSpecDefault) String() string {
	return fmt.Sprintf("[PUT /api/v1/applications/{name}/spec][%d] ApplicationService_UpdateSpec default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceUpdateSpecDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceUpdateSpecDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
