// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationServicePatchResourceReader is a Reader for the ApplicationServicePatchResource structure.
type ApplicationServicePatchResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServicePatchResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServicePatchResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServicePatchResourceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServicePatchResourceOK creates a ApplicationServicePatchResourceOK with default headers values
func NewApplicationServicePatchResourceOK() *ApplicationServicePatchResourceOK {
	return &ApplicationServicePatchResourceOK{}
}

/* ApplicationServicePatchResourceOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServicePatchResourceOK struct {
	Payload *models.ApplicationApplicationResourceResponse
}

// IsSuccess returns true when this application service patch resource o k response has a 2xx status code
func (o *ApplicationServicePatchResourceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application service patch resource o k response has a 3xx status code
func (o *ApplicationServicePatchResourceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application service patch resource o k response has a 4xx status code
func (o *ApplicationServicePatchResourceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application service patch resource o k response has a 5xx status code
func (o *ApplicationServicePatchResourceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application service patch resource o k response a status code equal to that given
func (o *ApplicationServicePatchResourceOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationServicePatchResourceOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications/{name}/resource][%d] applicationServicePatchResourceOK  %+v", 200, o.Payload)
}

func (o *ApplicationServicePatchResourceOK) String() string {
	return fmt.Sprintf("[POST /api/v1/applications/{name}/resource][%d] applicationServicePatchResourceOK  %+v", 200, o.Payload)
}

func (o *ApplicationServicePatchResourceOK) GetPayload() *models.ApplicationApplicationResourceResponse {
	return o.Payload
}

func (o *ApplicationServicePatchResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationApplicationResourceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServicePatchResourceDefault creates a ApplicationServicePatchResourceDefault with default headers values
func NewApplicationServicePatchResourceDefault(code int) *ApplicationServicePatchResourceDefault {
	return &ApplicationServicePatchResourceDefault{
		_statusCode: code,
	}
}

/* ApplicationServicePatchResourceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServicePatchResourceDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service patch resource default response
func (o *ApplicationServicePatchResourceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application service patch resource default response has a 2xx status code
func (o *ApplicationServicePatchResourceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application service patch resource default response has a 3xx status code
func (o *ApplicationServicePatchResourceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application service patch resource default response has a 4xx status code
func (o *ApplicationServicePatchResourceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application service patch resource default response has a 5xx status code
func (o *ApplicationServicePatchResourceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application service patch resource default response a status code equal to that given
func (o *ApplicationServicePatchResourceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationServicePatchResourceDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications/{name}/resource][%d] ApplicationService_PatchResource default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServicePatchResourceDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/applications/{name}/resource][%d] ApplicationService_PatchResource default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServicePatchResourceDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServicePatchResourceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
