// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationServicePatchReader is a Reader for the ApplicationServicePatch structure.
type ApplicationServicePatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServicePatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServicePatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServicePatchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServicePatchOK creates a ApplicationServicePatchOK with default headers values
func NewApplicationServicePatchOK() *ApplicationServicePatchOK {
	return &ApplicationServicePatchOK{}
}

/* ApplicationServicePatchOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServicePatchOK struct {
	Payload *models.V1alpha1Application
}

// IsSuccess returns true when this application service patch o k response has a 2xx status code
func (o *ApplicationServicePatchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application service patch o k response has a 3xx status code
func (o *ApplicationServicePatchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application service patch o k response has a 4xx status code
func (o *ApplicationServicePatchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application service patch o k response has a 5xx status code
func (o *ApplicationServicePatchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application service patch o k response a status code equal to that given
func (o *ApplicationServicePatchOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationServicePatchOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/applications/{name}][%d] applicationServicePatchOK  %+v", 200, o.Payload)
}

func (o *ApplicationServicePatchOK) String() string {
	return fmt.Sprintf("[PATCH /api/v1/applications/{name}][%d] applicationServicePatchOK  %+v", 200, o.Payload)
}

func (o *ApplicationServicePatchOK) GetPayload() *models.V1alpha1Application {
	return o.Payload
}

func (o *ApplicationServicePatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServicePatchDefault creates a ApplicationServicePatchDefault with default headers values
func NewApplicationServicePatchDefault(code int) *ApplicationServicePatchDefault {
	return &ApplicationServicePatchDefault{
		_statusCode: code,
	}
}

/* ApplicationServicePatchDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServicePatchDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service patch default response
func (o *ApplicationServicePatchDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application service patch default response has a 2xx status code
func (o *ApplicationServicePatchDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application service patch default response has a 3xx status code
func (o *ApplicationServicePatchDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application service patch default response has a 4xx status code
func (o *ApplicationServicePatchDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application service patch default response has a 5xx status code
func (o *ApplicationServicePatchDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application service patch default response a status code equal to that given
func (o *ApplicationServicePatchDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationServicePatchDefault) Error() string {
	return fmt.Sprintf("[PATCH /api/v1/applications/{name}][%d] ApplicationService_Patch default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServicePatchDefault) String() string {
	return fmt.Sprintf("[PATCH /api/v1/applications/{name}][%d] ApplicationService_Patch default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServicePatchDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServicePatchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
