// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationServiceGetManifestsWithFilesReader is a Reader for the ApplicationServiceGetManifestsWithFiles structure.
type ApplicationServiceGetManifestsWithFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceGetManifestsWithFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceGetManifestsWithFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceGetManifestsWithFilesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceGetManifestsWithFilesOK creates a ApplicationServiceGetManifestsWithFilesOK with default headers values
func NewApplicationServiceGetManifestsWithFilesOK() *ApplicationServiceGetManifestsWithFilesOK {
	return &ApplicationServiceGetManifestsWithFilesOK{}
}

/* ApplicationServiceGetManifestsWithFilesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceGetManifestsWithFilesOK struct {
	Payload *models.RepositoryManifestResponse
}

// IsSuccess returns true when this application service get manifests with files o k response has a 2xx status code
func (o *ApplicationServiceGetManifestsWithFilesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application service get manifests with files o k response has a 3xx status code
func (o *ApplicationServiceGetManifestsWithFilesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application service get manifests with files o k response has a 4xx status code
func (o *ApplicationServiceGetManifestsWithFilesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application service get manifests with files o k response has a 5xx status code
func (o *ApplicationServiceGetManifestsWithFilesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application service get manifests with files o k response a status code equal to that given
func (o *ApplicationServiceGetManifestsWithFilesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationServiceGetManifestsWithFilesOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications/manifestsWithFiles][%d] applicationServiceGetManifestsWithFilesOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceGetManifestsWithFilesOK) String() string {
	return fmt.Sprintf("[POST /api/v1/applications/manifestsWithFiles][%d] applicationServiceGetManifestsWithFilesOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceGetManifestsWithFilesOK) GetPayload() *models.RepositoryManifestResponse {
	return o.Payload
}

func (o *ApplicationServiceGetManifestsWithFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RepositoryManifestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceGetManifestsWithFilesDefault creates a ApplicationServiceGetManifestsWithFilesDefault with default headers values
func NewApplicationServiceGetManifestsWithFilesDefault(code int) *ApplicationServiceGetManifestsWithFilesDefault {
	return &ApplicationServiceGetManifestsWithFilesDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceGetManifestsWithFilesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceGetManifestsWithFilesDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service get manifests with files default response
func (o *ApplicationServiceGetManifestsWithFilesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application service get manifests with files default response has a 2xx status code
func (o *ApplicationServiceGetManifestsWithFilesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application service get manifests with files default response has a 3xx status code
func (o *ApplicationServiceGetManifestsWithFilesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application service get manifests with files default response has a 4xx status code
func (o *ApplicationServiceGetManifestsWithFilesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application service get manifests with files default response has a 5xx status code
func (o *ApplicationServiceGetManifestsWithFilesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application service get manifests with files default response a status code equal to that given
func (o *ApplicationServiceGetManifestsWithFilesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationServiceGetManifestsWithFilesDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications/manifestsWithFiles][%d] ApplicationService_GetManifestsWithFiles default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceGetManifestsWithFilesDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/applications/manifestsWithFiles][%d] ApplicationService_GetManifestsWithFiles default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceGetManifestsWithFilesDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceGetManifestsWithFilesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
