// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// ApplicationServiceGetReader is a Reader for the ApplicationServiceGet structure.
type ApplicationServiceGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceGetOK creates a ApplicationServiceGetOK with default headers values
func NewApplicationServiceGetOK() *ApplicationServiceGetOK {
	return &ApplicationServiceGetOK{}
}

/* ApplicationServiceGetOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceGetOK struct {
	Payload *models.V1alpha1Application
}

// IsSuccess returns true when this application service get o k response has a 2xx status code
func (o *ApplicationServiceGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application service get o k response has a 3xx status code
func (o *ApplicationServiceGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application service get o k response has a 4xx status code
func (o *ApplicationServiceGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this application service get o k response has a 5xx status code
func (o *ApplicationServiceGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this application service get o k response a status code equal to that given
func (o *ApplicationServiceGetOK) IsCode(code int) bool {
	return code == 200
}

func (o *ApplicationServiceGetOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}][%d] applicationServiceGetOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceGetOK) String() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}][%d] applicationServiceGetOK  %+v", 200, o.Payload)
}

func (o *ApplicationServiceGetOK) GetPayload() *models.V1alpha1Application {
	return o.Payload
}

func (o *ApplicationServiceGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceGetDefault creates a ApplicationServiceGetDefault with default headers values
func NewApplicationServiceGetDefault(code int) *ApplicationServiceGetDefault {
	return &ApplicationServiceGetDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceGetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceGetDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service get default response
func (o *ApplicationServiceGetDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this application service get default response has a 2xx status code
func (o *ApplicationServiceGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this application service get default response has a 3xx status code
func (o *ApplicationServiceGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this application service get default response has a 4xx status code
func (o *ApplicationServiceGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this application service get default response has a 5xx status code
func (o *ApplicationServiceGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this application service get default response a status code equal to that given
func (o *ApplicationServiceGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ApplicationServiceGetDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}][%d] ApplicationService_Get default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceGetDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}][%d] ApplicationService_Get default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationServiceGetDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
