// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// RepositoryServiceUpdateRepositoryReader is a Reader for the RepositoryServiceUpdateRepository structure.
type RepositoryServiceUpdateRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceUpdateRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceUpdateRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceUpdateRepositoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceUpdateRepositoryOK creates a RepositoryServiceUpdateRepositoryOK with default headers values
func NewRepositoryServiceUpdateRepositoryOK() *RepositoryServiceUpdateRepositoryOK {
	return &RepositoryServiceUpdateRepositoryOK{}
}

/* RepositoryServiceUpdateRepositoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceUpdateRepositoryOK struct {
	Payload *models.V1alpha1Repository
}

// IsSuccess returns true when this repository service update repository o k response has a 2xx status code
func (o *RepositoryServiceUpdateRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repository service update repository o k response has a 3xx status code
func (o *RepositoryServiceUpdateRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repository service update repository o k response has a 4xx status code
func (o *RepositoryServiceUpdateRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repository service update repository o k response has a 5xx status code
func (o *RepositoryServiceUpdateRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repository service update repository o k response a status code equal to that given
func (o *RepositoryServiceUpdateRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *RepositoryServiceUpdateRepositoryOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repositories/{repo.repo}][%d] repositoryServiceUpdateRepositoryOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceUpdateRepositoryOK) String() string {
	return fmt.Sprintf("[PUT /api/v1/repositories/{repo.repo}][%d] repositoryServiceUpdateRepositoryOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceUpdateRepositoryOK) GetPayload() *models.V1alpha1Repository {
	return o.Payload
}

func (o *RepositoryServiceUpdateRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceUpdateRepositoryDefault creates a RepositoryServiceUpdateRepositoryDefault with default headers values
func NewRepositoryServiceUpdateRepositoryDefault(code int) *RepositoryServiceUpdateRepositoryDefault {
	return &RepositoryServiceUpdateRepositoryDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceUpdateRepositoryDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceUpdateRepositoryDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service update repository default response
func (o *RepositoryServiceUpdateRepositoryDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this repository service update repository default response has a 2xx status code
func (o *RepositoryServiceUpdateRepositoryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this repository service update repository default response has a 3xx status code
func (o *RepositoryServiceUpdateRepositoryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this repository service update repository default response has a 4xx status code
func (o *RepositoryServiceUpdateRepositoryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this repository service update repository default response has a 5xx status code
func (o *RepositoryServiceUpdateRepositoryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this repository service update repository default response a status code equal to that given
func (o *RepositoryServiceUpdateRepositoryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RepositoryServiceUpdateRepositoryDefault) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repositories/{repo.repo}][%d] RepositoryService_UpdateRepository default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceUpdateRepositoryDefault) String() string {
	return fmt.Sprintf("[PUT /api/v1/repositories/{repo.repo}][%d] RepositoryService_UpdateRepository default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceUpdateRepositoryDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceUpdateRepositoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
