// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// RepositoryServiceListAppsReader is a Reader for the RepositoryServiceListApps structure.
type RepositoryServiceListAppsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceListAppsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceListAppsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceListAppsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceListAppsOK creates a RepositoryServiceListAppsOK with default headers values
func NewRepositoryServiceListAppsOK() *RepositoryServiceListAppsOK {
	return &RepositoryServiceListAppsOK{}
}

/* RepositoryServiceListAppsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceListAppsOK struct {
	Payload *models.RepositoryRepoAppsResponse
}

// IsSuccess returns true when this repository service list apps o k response has a 2xx status code
func (o *RepositoryServiceListAppsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repository service list apps o k response has a 3xx status code
func (o *RepositoryServiceListAppsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repository service list apps o k response has a 4xx status code
func (o *RepositoryServiceListAppsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repository service list apps o k response has a 5xx status code
func (o *RepositoryServiceListAppsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repository service list apps o k response a status code equal to that given
func (o *RepositoryServiceListAppsOK) IsCode(code int) bool {
	return code == 200
}

func (o *RepositoryServiceListAppsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}/apps][%d] repositoryServiceListAppsOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceListAppsOK) String() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}/apps][%d] repositoryServiceListAppsOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceListAppsOK) GetPayload() *models.RepositoryRepoAppsResponse {
	return o.Payload
}

func (o *RepositoryServiceListAppsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RepositoryRepoAppsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceListAppsDefault creates a RepositoryServiceListAppsDefault with default headers values
func NewRepositoryServiceListAppsDefault(code int) *RepositoryServiceListAppsDefault {
	return &RepositoryServiceListAppsDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceListAppsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceListAppsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service list apps default response
func (o *RepositoryServiceListAppsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this repository service list apps default response has a 2xx status code
func (o *RepositoryServiceListAppsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this repository service list apps default response has a 3xx status code
func (o *RepositoryServiceListAppsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this repository service list apps default response has a 4xx status code
func (o *RepositoryServiceListAppsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this repository service list apps default response has a 5xx status code
func (o *RepositoryServiceListAppsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this repository service list apps default response a status code equal to that given
func (o *RepositoryServiceListAppsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RepositoryServiceListAppsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}/apps][%d] RepositoryService_ListApps default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceListAppsDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}/apps][%d] RepositoryService_ListApps default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceListAppsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceListAppsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
