// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// RepositoryServiceValidateAccessReader is a Reader for the RepositoryServiceValidateAccess structure.
type RepositoryServiceValidateAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceValidateAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceValidateAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceValidateAccessDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceValidateAccessOK creates a RepositoryServiceValidateAccessOK with default headers values
func NewRepositoryServiceValidateAccessOK() *RepositoryServiceValidateAccessOK {
	return &RepositoryServiceValidateAccessOK{}
}

/* RepositoryServiceValidateAccessOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceValidateAccessOK struct {
	Payload models.RepositoryRepoResponse
}

// IsSuccess returns true when this repository service validate access o k response has a 2xx status code
func (o *RepositoryServiceValidateAccessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repository service validate access o k response has a 3xx status code
func (o *RepositoryServiceValidateAccessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repository service validate access o k response has a 4xx status code
func (o *RepositoryServiceValidateAccessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repository service validate access o k response has a 5xx status code
func (o *RepositoryServiceValidateAccessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repository service validate access o k response a status code equal to that given
func (o *RepositoryServiceValidateAccessOK) IsCode(code int) bool {
	return code == 200
}

func (o *RepositoryServiceValidateAccessOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] repositoryServiceValidateAccessOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceValidateAccessOK) String() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] repositoryServiceValidateAccessOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceValidateAccessOK) GetPayload() models.RepositoryRepoResponse {
	return o.Payload
}

func (o *RepositoryServiceValidateAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceValidateAccessDefault creates a RepositoryServiceValidateAccessDefault with default headers values
func NewRepositoryServiceValidateAccessDefault(code int) *RepositoryServiceValidateAccessDefault {
	return &RepositoryServiceValidateAccessDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceValidateAccessDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceValidateAccessDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service validate access default response
func (o *RepositoryServiceValidateAccessDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this repository service validate access default response has a 2xx status code
func (o *RepositoryServiceValidateAccessDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this repository service validate access default response has a 3xx status code
func (o *RepositoryServiceValidateAccessDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this repository service validate access default response has a 4xx status code
func (o *RepositoryServiceValidateAccessDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this repository service validate access default response has a 5xx status code
func (o *RepositoryServiceValidateAccessDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this repository service validate access default response a status code equal to that given
func (o *RepositoryServiceValidateAccessDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RepositoryServiceValidateAccessDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] RepositoryService_ValidateAccess default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceValidateAccessDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] RepositoryService_ValidateAccess default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceValidateAccessDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceValidateAccessDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
