// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// RepositoryServiceCreateRepositoryReader is a Reader for the RepositoryServiceCreateRepository structure.
type RepositoryServiceCreateRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceCreateRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceCreateRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceCreateRepositoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceCreateRepositoryOK creates a RepositoryServiceCreateRepositoryOK with default headers values
func NewRepositoryServiceCreateRepositoryOK() *RepositoryServiceCreateRepositoryOK {
	return &RepositoryServiceCreateRepositoryOK{}
}

/* RepositoryServiceCreateRepositoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceCreateRepositoryOK struct {
	Payload *models.V1alpha1Repository
}

// IsSuccess returns true when this repository service create repository o k response has a 2xx status code
func (o *RepositoryServiceCreateRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repository service create repository o k response has a 3xx status code
func (o *RepositoryServiceCreateRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repository service create repository o k response has a 4xx status code
func (o *RepositoryServiceCreateRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repository service create repository o k response has a 5xx status code
func (o *RepositoryServiceCreateRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repository service create repository o k response a status code equal to that given
func (o *RepositoryServiceCreateRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *RepositoryServiceCreateRepositoryOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories][%d] repositoryServiceCreateRepositoryOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceCreateRepositoryOK) String() string {
	return fmt.Sprintf("[POST /api/v1/repositories][%d] repositoryServiceCreateRepositoryOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceCreateRepositoryOK) GetPayload() *models.V1alpha1Repository {
	return o.Payload
}

func (o *RepositoryServiceCreateRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceCreateRepositoryDefault creates a RepositoryServiceCreateRepositoryDefault with default headers values
func NewRepositoryServiceCreateRepositoryDefault(code int) *RepositoryServiceCreateRepositoryDefault {
	return &RepositoryServiceCreateRepositoryDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceCreateRepositoryDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceCreateRepositoryDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service create repository default response
func (o *RepositoryServiceCreateRepositoryDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this repository service create repository default response has a 2xx status code
func (o *RepositoryServiceCreateRepositoryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this repository service create repository default response has a 3xx status code
func (o *RepositoryServiceCreateRepositoryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this repository service create repository default response has a 4xx status code
func (o *RepositoryServiceCreateRepositoryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this repository service create repository default response has a 5xx status code
func (o *RepositoryServiceCreateRepositoryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this repository service create repository default response a status code equal to that given
func (o *RepositoryServiceCreateRepositoryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RepositoryServiceCreateRepositoryDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories][%d] RepositoryService_CreateRepository default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceCreateRepositoryDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/repositories][%d] RepositoryService_CreateRepository default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceCreateRepositoryDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceCreateRepositoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
