// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// RepositoryServiceGetAppDetailsReader is a Reader for the RepositoryServiceGetAppDetails structure.
type RepositoryServiceGetAppDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceGetAppDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceGetAppDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceGetAppDetailsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceGetAppDetailsOK creates a RepositoryServiceGetAppDetailsOK with default headers values
func NewRepositoryServiceGetAppDetailsOK() *RepositoryServiceGetAppDetailsOK {
	return &RepositoryServiceGetAppDetailsOK{}
}

/* RepositoryServiceGetAppDetailsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceGetAppDetailsOK struct {
	Payload *models.RepositoryRepoAppDetailsResponse
}

// IsSuccess returns true when this repository service get app details o k response has a 2xx status code
func (o *RepositoryServiceGetAppDetailsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repository service get app details o k response has a 3xx status code
func (o *RepositoryServiceGetAppDetailsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repository service get app details o k response has a 4xx status code
func (o *RepositoryServiceGetAppDetailsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repository service get app details o k response has a 5xx status code
func (o *RepositoryServiceGetAppDetailsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repository service get app details o k response a status code equal to that given
func (o *RepositoryServiceGetAppDetailsOK) IsCode(code int) bool {
	return code == 200
}

func (o *RepositoryServiceGetAppDetailsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{source.repoURL}/appdetails][%d] repositoryServiceGetAppDetailsOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceGetAppDetailsOK) String() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{source.repoURL}/appdetails][%d] repositoryServiceGetAppDetailsOK  %+v", 200, o.Payload)
}

func (o *RepositoryServiceGetAppDetailsOK) GetPayload() *models.RepositoryRepoAppDetailsResponse {
	return o.Payload
}

func (o *RepositoryServiceGetAppDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RepositoryRepoAppDetailsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceGetAppDetailsDefault creates a RepositoryServiceGetAppDetailsDefault with default headers values
func NewRepositoryServiceGetAppDetailsDefault(code int) *RepositoryServiceGetAppDetailsDefault {
	return &RepositoryServiceGetAppDetailsDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceGetAppDetailsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceGetAppDetailsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service get app details default response
func (o *RepositoryServiceGetAppDetailsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this repository service get app details default response has a 2xx status code
func (o *RepositoryServiceGetAppDetailsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this repository service get app details default response has a 3xx status code
func (o *RepositoryServiceGetAppDetailsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this repository service get app details default response has a 4xx status code
func (o *RepositoryServiceGetAppDetailsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this repository service get app details default response has a 5xx status code
func (o *RepositoryServiceGetAppDetailsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this repository service get app details default response a status code equal to that given
func (o *RepositoryServiceGetAppDetailsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RepositoryServiceGetAppDetailsDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{source.repoURL}/appdetails][%d] RepositoryService_GetAppDetails default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceGetAppDetailsDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{source.repoURL}/appdetails][%d] RepositoryService_GetAppDetails default  %+v", o._statusCode, o.Payload)
}

func (o *RepositoryServiceGetAppDetailsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceGetAppDetailsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
