// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stefanmcshane/go-argocd/argocd/models"
)

// RepoCredsServiceDeleteRepositoryCredentialsReader is a Reader for the RepoCredsServiceDeleteRepositoryCredentials structure.
type RepoCredsServiceDeleteRepositoryCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoCredsServiceDeleteRepositoryCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoCredsServiceDeleteRepositoryCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepoCredsServiceDeleteRepositoryCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepoCredsServiceDeleteRepositoryCredentialsOK creates a RepoCredsServiceDeleteRepositoryCredentialsOK with default headers values
func NewRepoCredsServiceDeleteRepositoryCredentialsOK() *RepoCredsServiceDeleteRepositoryCredentialsOK {
	return &RepoCredsServiceDeleteRepositoryCredentialsOK{}
}

/* RepoCredsServiceDeleteRepositoryCredentialsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepoCredsServiceDeleteRepositoryCredentialsOK struct {
	Payload models.RepocredsRepoCredsResponse
}

// IsSuccess returns true when this repo creds service delete repository credentials o k response has a 2xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repo creds service delete repository credentials o k response has a 3xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repo creds service delete repository credentials o k response has a 4xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repo creds service delete repository credentials o k response has a 5xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repo creds service delete repository credentials o k response a status code equal to that given
func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) IsCode(code int) bool {
	return code == 200
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repocreds/{url}][%d] repoCredsServiceDeleteRepositoryCredentialsOK  %+v", 200, o.Payload)
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/repocreds/{url}][%d] repoCredsServiceDeleteRepositoryCredentialsOK  %+v", 200, o.Payload)
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) GetPayload() models.RepocredsRepoCredsResponse {
	return o.Payload
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepoCredsServiceDeleteRepositoryCredentialsDefault creates a RepoCredsServiceDeleteRepositoryCredentialsDefault with default headers values
func NewRepoCredsServiceDeleteRepositoryCredentialsDefault(code int) *RepoCredsServiceDeleteRepositoryCredentialsDefault {
	return &RepoCredsServiceDeleteRepositoryCredentialsDefault{
		_statusCode: code,
	}
}

/* RepoCredsServiceDeleteRepositoryCredentialsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepoCredsServiceDeleteRepositoryCredentialsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repo creds service delete repository credentials default response
func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this repo creds service delete repository credentials default response has a 2xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this repo creds service delete repository credentials default response has a 3xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this repo creds service delete repository credentials default response has a 4xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this repo creds service delete repository credentials default response has a 5xx status code
func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this repo creds service delete repository credentials default response a status code equal to that given
func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repocreds/{url}][%d] RepoCredsService_DeleteRepositoryCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) String() string {
	return fmt.Sprintf("[DELETE /api/v1/repocreds/{url}][%d] RepoCredsService_DeleteRepositoryCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepoCredsServiceDeleteRepositoryCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
